# Generated by Django 5.0.1 on 2024-02-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='global_click_counter',
        ),
        migrations.AddField(
            model_name='visitors',
            name='global_click_counter_register',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='global_click_counter_result',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
