# Generated by Django 5.0.1 on 2024-02-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_visitors_global_click_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='global_click_counter_gift',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='global_click_counter_register',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='global_click_counter_result',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='name',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
