# Generated by Django 5.0.1 on 2024-02-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_visitors_global_click_counter_gift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
